name: spec_dart
version: 0.1.0-beta
author: SoftHai <softhai@gmx.de>
description: Spec.Dart is an BDD Framework for testing dart applications
homepage: https://github.com/SoftHai/Spec.Dart
documentation: https://github.com/SoftHai/Spec.Dart
dependencies:
  unittest: any
